Урок 4. Задание 2. Пробую использовать ретрофит. Что-то не получается...
24025-24025 E: FATAL EXCEPTION: main
    Process: com.artmil.mygallery, PID: 24025
    java.lang.IllegalArgumentException: Unable to create call adapter for io.reactivex.Observable<java.lang.String>
        for method RetrofitService.getUser
        at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
        at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:237)
        at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:162)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
        at java.lang.reflect.Proxy.invoke(Proxy.java:813)
        at $Proxy3.getUser(Unknown Source)
        at com.artmil.mygallery.lesson4.task2.RetrofitApi.requestServer(RetrofitApi.java:20)
        at com.artmil.mygallery.lesson4.task2.RetrofitPresenter.getString(RetrofitPresenter.java:17)
        at com.artmil.mygallery.lesson4.task2.RetorfitActivity.pressButton(RetorfitActivity.java:36)
        at com.artmil.mygallery.lesson4.task2.RetorfitActivity_ViewBinding$1.doClick(RetorfitActivity_ViewBinding.java:38)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
        at android.view.View.performClick(View.java:5646)
        at android.view.View$PerformClick.run(View.java:22473)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6517)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.IllegalArgumentException: Could not locate call adapter for io.reactivex.Observable<java.lang.String>.
      Tried:
       * retrofit2.adapter.rxjava.RxJavaCallAdapterFactory
       * retrofit2.ExecutorCallAdapterFactory
        at retrofit2.Retrofit.nextCallAdapter(Retrofit.java:241)
        at retrofit2.Retrofit.callAdapter(Retrofit.java:205)
        at retrofit2.ServiceMethod$Builder.createCallAdapter(ServiceMethod.java:235)
        	... 19 more